[package]
name = "forge"
version.workspace = true
edition.workspace = true
publish.workspace = true

[[bin]]
name = "forge"
path = "src/bin/forge.rs"

[dependencies]
domain = { path = "../core/domain" }
db = { path = "../core/db" }
workflow = { path = "../core/workflow" }
integrations = { path = "../integrations" }

[[bin]]
name = "re-workflow"
path = "src/bin/re_workflow.rs"
