export { BaseService } from './base-service'
export { ServiceError } from './service-error'
export { InMemoryServiceQueue } from './service-queue'
export { ServiceRegistry } from './service-registry'
export {
  RoleCatalog,
  normalizeRoleAlias,
  type RoleDefinition,
  type RoleScope,
  type ResolvedRole,
} from './role'
export type {
  AuditPort,
  AuthorizationDecision,
  AuthorizationPort,
  AuthorizationRequest,
  DomainEventPort,
  ServiceActor,
  ServiceAuditEvent,
  ServiceCapability,
  ServiceContext,
  ServiceDescriptor,
  ServiceDomainEvent,
  ServiceEndpoint,
  ServiceEnvelope,
  ServiceEnvelopeFor,
  ServiceErrorShape,
  ServiceExecutionMode,
  ServiceExecutionPolicy,
  ServiceFailure,
  ServiceInfrastructure,
  ServiceOperationContract,
  ServiceOperationDefinition,
  ServiceOperationDefinitions,
  ServiceOperationKind,
  ServiceOperationMap,
  ServiceOperationName,
  ServiceOperationRequest,
  ServiceOperationResponse,
  ServicePrincipal,
  ServiceQueue,
  ServiceQueueItem,
  ServiceResourceContext,
  ServiceResult,
  ServiceRouter,
  ServiceSuccess,
} from './types'
