[package]
name = "server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
auth = { path = "../core/auth" }
chrono.workspace = true
db = { path = "../core/db" }
domain = { path = "../core/domain" }
integrations = { path = "../integrations" }
serde_json.workspace = true
service = { path = "../core/service" }
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true
