[package]
name = "server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
axum.workspace = true
auth = { path = "../core/auth" }
chrono.workspace = true
db = { path = "../core/db" }
domain = { path = "../core/domain" }
serde.workspace = true
serde_json.workspace = true
service = { path = "../core/service" }
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

