export { PropertyService } from '@/legacy/services/property/property-service'
export type { PropertyRepository } from '@/legacy/services/property/repository'
export {
  PROPERTY_OPERATIONS,
  type FilterPropertiesRequest,
  type FindPropertyByAddressRequest,
  type GetPropertiesForPersonRequest,
  type GetPropertyBySlugRequest,
  type GetPropertyIntroRequest,
  type GetPropertyRequest,
  type GetSimilarPropertiesRequest,
  type ListPropertiesRequest,
  type ListPropertySlugsRequest,
  type PersonPropertyContextDto,
  type PersonPropertyRelation,
  type PropertyAddressDto,
  type PropertyDto,
  type PropertyEnvelope,
  type PropertyFilterInput,
  type PropertyIntro,
  type PropertyInventoryPage,
  type PropertySummary,
  type PropertyForPersonDto,
  type PropertyOperationMap,
  type PropertyOperationName,
  type SetPropertyDisplayNameRequest,
  type SetPropertyStatusRequest,
  type UpsertPropertyForPersonRequest,
} from '@/legacy/services/property/types'
