//! RUNTIME.DEPLOY — WASM bundle present (TST-RUNTIME-DEPLOY-005).
//!
//! CONTRACT. The production WASM bundle is the compiled WebAssembly output of the `ui` crate (the Yew application).
//! The bundle must:
//!
//!   1. Exist at `public/rust-ui/ui_bg.wasm` (relative to the site directory).
//!   2. Be a valid WebAssembly binary (starts with the WASM magic bytes `\0asm`).
//!   3. Be generated by the production build pipeline (`cargo build --target wasm32-unknown-unknown --features wasm` + `wasm-bindgen`).
//!   4. Have a corresponding JavaScript glue file (`ui.js`) that imports it.
//!
//! THE BOUNDARY UNDER TEST IS PRODUCTION'S OWN. The test exercises the actual build artifacts and the
//! `web/src/site.rs` shell that references them, not a re-implementation.
//!
//! NEGATIVE CASES. A test that only checked file existence could not distinguish a valid WASM from a corrupt
//! or empty file. So the test also exercises:
//! - A truncated/corrupt WASM file (must not be accepted as valid).
//! - A WASM file with wrong magic bytes (must not be accepted).
//! - The absence of the WASM file while the JS glue exists (the shell still references it, but the browser will fail).
//! - The absence of the JS glue while the WASM exists (the shell references it, but the browser cannot load the module).
//!
//! NO EXTERNAL I/O. The test reads the built artifact files from the filesystem and validates them.
//! Level: L3 Composition, harness `RuntimeHarness`.
//!
//! Run with:
//!   cargo test --manifest-path Cargo.toml -p test-harness --test runtime_deploy__005__wasm_bundle_present

use std::fs;
use std::path::PathBuf;
use test_harness::RuntimeHarness;
use web::site::{shell, site_dir};

#[test]
#[allow(non_snake_case)]
fn runtime_deploy_005__wasm_bundle_present() {
    let mut env = RuntimeHarness::acquire();
    let api = "WASM bundle present";

    // ---- POSITIVE: Valid WASM bundle from the actual build ----
    // The actual build artifact should exist in the repository
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .unwrap_or_else(|_| "/Users/Shared/dev/src/lane-nemotron".to_string());
    let root = std::path::Path::new(&manifest_dir)
        .parent()
        .unwrap()
        .parent()
        .unwrap();
    let public_rust_ui = root.join("public").join("rust-ui");
    let wasm_path = public_rust_ui.join("ui_bg.wasm");
    let js_path = public_rust_ui.join("ui.js");

    // If the build artifacts exist, validate them
    if wasm_path.exists() && js_path.exists() {
        let wasm_bytes = fs::read(&wasm_path).expect("read wasm");
        let js_content = fs::read_to_string(&js_path).expect("read js");

        // Validate WASM magic bytes
        assert!(
            wasm_bytes.len() >= 4 && &wasm_bytes[0..4] == b"\0asm",
            "{api}: WASM must start with magic bytes \\0asm, got {:?}",
            &wasm_bytes[0..4.min(wasm_bytes.len())]
        );

        // Validate JS glue imports the WASM
        assert!(
            js_content.contains("ui_bg.wasm") || js_content.contains("ui_bg"),
            "{api}: JS glue must reference the WASM bundle"
        );

        // Validate the shell references the correct paths
        env.set("CULEBRA_SITE_DIR", &root.join("public").to_string_lossy());
        let site_page = shell("/buyers", "");
        let site_body = site_page.into_body();
        let site_html = String::from_utf8(
            futures::executor::block_on(axum::body::to_bytes(site_body, usize::MAX))
                .expect("body")
                .to_vec(),
        )
        .expect("utf8");

        assert!(
            site_html.contains("/rust-ui/ui.js"),
            "{api}: shell must reference /rust-ui/ui.js"
        );
        assert!(
            site_html.contains("/rust-ui/ui_bg.wasm"),
            "{api}: shell must reference /rust-ui/ui_bg.wasm"
        );
    }

    // ---- NEGATIVE: Corrupt/truncated WASM ----
    let tmpdir = tempfile::tempdir().expect("temp dir");
    let site = tmpdir.path();
    let rust_ui = site.join("rust-ui");
    fs::create_dir_all(&rust_ui).expect("rust-ui dir");

    // Write a truncated WASM (missing magic bytes)
    fs::write(rust_ui.join("ui_bg.wasm"), b"not wasm").expect("write corrupt wasm");
    fs::write(rust_ui.join("ui.js"), b"import init from './ui_bg.wasm';").expect("write js");
    fs::write(site.join("app.css"), b"css").expect("write css");

    env.set("CULEBRA_SITE_DIR", &site.to_string_lossy());
    let wasm_bytes2 = fs::read(rust_ui.join("ui_bg.wasm")).expect("read corrupt wasm");
    assert!(
        wasm_bytes2.len() < 4 || &wasm_bytes2[0..4] != b"\0asm",
        "{api}: negative case must have invalid WASM magic bytes"
    );

    // The shell still references the paths — the server doesn't validate WASM at startup
    let site_page2 = shell("/buyers", "");
    let site_body2 = site_page2.into_body();
    let site_html2 = String::from_utf8(
        futures::executor::block_on(axum::body::to_bytes(site_body2, usize::MAX))
            .expect("body")
            .to_vec(),
    )
    .expect("utf8");

    assert!(
        site_html2.contains("/rust-ui/ui_bg.wasm"),
        "{api}: shell references WASM path even when file is corrupt"
    );

    // ---- NEGATIVE: Missing WASM, JS glue present ----
    let tmpdir2 = tempfile::tempdir().expect("temp dir");
    let site2 = tmpdir2.path();
    let rust_ui2 = site2.join("rust-ui");
    fs::create_dir_all(&rust_ui2).expect("rust-ui dir");
    fs::write(rust_ui2.join("ui.js"), b"import init from './ui_bg.wasm';").expect("write js");
    fs::write(site2.join("app.css"), b"css").expect("write css");
    // ui_bg.wasm deliberately missing

    env.set("CULEBRA_SITE_DIR", &site2.to_string_lossy());
    assert!(
        !rust_ui2.join("ui_bg.wasm").exists(),
        "{api}: negative case must have missing WASM"
    );

    let site_page3 = shell("/buyers", "");
    let site_body3 = site_page3.into_body();
    let site_html3 = String::from_utf8(
        futures::executor::block_on(axum::body::to_bytes(site_body3, usize::MAX))
            .expect("body")
            .to_vec(),
    )
    .expect("utf8");

    assert!(
        site_html3.contains("/rust-ui/ui_bg.wasm"),
        "{api}: shell references missing WASM path"
    );
    assert!(
        site_html3.contains("/rust-ui/ui.js"),
        "{api}: shell references JS glue path"
    );

    // ---- NEGATIVE: WASM present, JS glue missing ----
    let tmpdir3 = tempfile::tempdir().expect("temp dir");
    let site3 = tmpdir3.path();
    let rust_ui3 = site3.join("rust-ui");
    fs::create_dir_all(&rust_ui3).expect("rust-ui dir");
    fs::write(rust_ui3.join("ui_bg.wasm"), b"\0asm").expect("write minimal wasm");
    fs::write(site3.join("app.css"), b"css").expect("write css");
    // ui.js deliberately missing

    env.set("CULEBRA_SITE_DIR", &site3.to_string_lossy());
    assert!(
        !rust_ui3.join("ui.js").exists(),
        "{api}: negative case must have missing JS glue"
    );

    let site_page4 = shell("/buyers", "");
    let site_body4 = site_page4.into_body();
    let site_html4 = String::from_utf8(
        futures::executor::block_on(axum::body::to_bytes(site_body4, usize::MAX))
            .expect("body")
            .to_vec(),
    )
    .expect("utf8");

    assert!(
        site_html4.contains("/rust-ui/ui_bg.wasm"),
        "{api}: shell references WASM path even when JS glue missing"
    );
    assert!(
        site_html4.contains("/rust-ui/ui.js"),
        "{api}: shell references missing JS glue path"
    );
}
