// ---------------------------------------------------------------------------
// ENG-FORGE-V5-23 / V5-24 — closing the serena and rtk seams.
//
// The catalog (forge-tool-catalog.ts) decides WHO may use a tool. This module is
// HOW the tool reaches the lane:
//
//   serena — an MCP server. OpenCode speaks MCP (`opencode mcp`), so the seam is
//            a registration, generated per position with only that position's
//            allowed operations.
//   rtk    — a CLI proxy that compacts command output. The seam is a shim
//            directory prepended to the lane's PATH, so the model keeps typing
//            `git status` and transparently gets `rtk git status`. The shim
//            `exec`s the proxy, so exit codes and failure truth are preserved.
//
// Neither tool is a decision the model makes, and neither may widen lane
// authority — the shims and the registration are built FROM the catalog.
// ---------------------------------------------------------------------------

import { mkdirSync, existsSync, writeFileSync, chmodSync } from 'node:fs'
import { join } from 'node:path'

import {
  FORGE_TOOL_CATALOG,
  SERENA_READ_OPERATIONS,
  SERENA_WRITE_OPERATIONS,
  resolveForgeToolPermissions,
  type ForgeToolRole,
} from './forge-tool-catalog'

/** Commands RTK compacts, and the subcommand that replaces them. */
export const RTK_COMMAND_MAP: Readonly<Record<string, string[]>> = {
  git: ['git'],
  ls: ['ls'],
  tree: ['tree'],
  gh: ['gh'],
}

export function rtkSupportsCommand(command: string): boolean {
  const head = command.trim().split(/\s+/)[0] ?? ''
  return head in RTK_COMMAND_MAP
}

/** The rtk invocation that stands in for a supported command. */
export function rtkRewrite(command: string): string | null {
  const trimmed = command.trim()
  if (!trimmed) return null
  const head = trimmed.split(/\s+/)[0] ?? ''
  const mapped = RTK_COMMAND_MAP[head]
  if (!mapped) return null
  const rest = trimmed.slice(head.length).trim()
  return `rtk ${mapped[0]}${rest ? ` ${rest}` : ''}`
}

/** Shim directory for a workspace. Generated, never committed. */
export function rtkShimDir(workspace: string): string {
  return join(workspace, '.forge', 'rtk-bin')
}

/**
 * Write the shims. Each one `exec`s rtk and forwards every argument, so the
 * caller's exit code IS rtk's exit code — a compaction must never turn failure
 * into success. A command rtk does not support is not shimmed at all, so the
 * real binary is used and the lane degrades to its existing path.
 */
export function writeRtkShims(input: { workspace: string; rtkBin: string }): string[] {
  const dir = rtkShimDir(input.workspace)
  mkdirSync(dir, { recursive: true })
  const written: string[] = []
  for (const command of Object.keys(RTK_COMMAND_MAP)) {
    const path = join(dir, command)
    writeFileSync(
      path,
      `#!/bin/sh\n# Generated by forge (V5-24). Transparent rtk proxy for \`${command}\`.\n` +
        `exec "${input.rtkBin}" ${command} "$@"\n`,
      'utf8',
    )
    chmodSync(path, 0o755)
    written.push(path)
  }
  return written
}

/**
 * The env a lane's child process should receive so RTK is transparent.
 * Returns the env unchanged when RTK is not granted to this position or the rtk
 * binary is absent — an unavailable tool degrades, it never half-applies.
 */
export function applyRtkToEnv<T extends Record<string, string | undefined>>(input: {
  role: ForgeToolRole
  env: T
  workspace: string
  rtkBin?: string | null
}): { env: T; applied: boolean; reason: string | null } {
  const grants = resolveForgeToolPermissions(input.role)
  const granted = FORGE_TOOL_CATALOG.rtk.roles.includes(input.role)
  if (!granted) return { env: input.env, applied: false, reason: 'rtk is not granted to this position' }
  if (!grants.grants.some((g) => g.tool === 'rtk')) {
    return { env: input.env, applied: false, reason: 'rtk seam is not wired' }
  }
  const rtkBin = input.rtkBin ?? 'rtk'
  writeRtkShims({ workspace: input.workspace, rtkBin })
  const dir = rtkShimDir(input.workspace)
  const current = input.env.PATH ?? ''
  return {
    // Preserve the caller's env type (a narrowed ProcessEnv is expected by the
    // harness config), which a plain spread would widen.
    env: { ...input.env, PATH: current ? `${dir}:${current}` : dir } as T,
    applied: true,
    reason: null,
  }
}


/**
 * Serena's semantic tool names as the MCP server exposes them.
 * Read and write are separated because the catalog grants them separately.
 */
export const SERENA_MCP_READ_TOOLS: readonly string[] = [
  'find_symbol',
  'find_referencing_symbols',
  'get_symbols_overview',
  'find_implementations',
  'get_diagnostics',
]

export const SERENA_MCP_WRITE_TOOLS: readonly string[] = [
  'rename_symbol',
  'replace_symbol_body',
  'insert_after_symbol',
  'insert_before_symbol',
]

/**
 * The MCP registration for this workspace.
 *
 * NOTE on per-role restriction: an MCP registration is PROJECT-WIDE — the server
 * is one process, so a role cannot have its own registration. Per-role authority
 * is therefore enforced by the catalog at the lane boundary (and by the lane's
 * allowed tool list), NOT by the registration. That is exactly the boundary the
 * story requires: Serena must never become its own authority layer.
 */
export function serenaMcpRegistration(input: {
  workspace: string
  serenaBin?: string
}): { name: string; command: string; args: string[] } {
  return {
    name: 'serena',
    command: input.serenaBin ?? 'serena',
    args: ['start-mcp-server', '--project', input.workspace],
  }
}

/** The shell command an operator runs to register it (opencode mcp add). */
export function serenaMcpAddCommand(input: {
  workspace: string
  serenaBin?: string
}): string {
  const reg = serenaMcpRegistration(input)
  return `opencode mcp add ${reg.name} -- ${reg.command} ${reg.args.join(' ')}`
}

/**
 * The Serena tools a position may be offered, derived from the catalog. A
 * position without a write grant gets the read tools ONLY — the same rule the
 * permission layer enforces, expressed as the tool list the lane advertises.
 */
export function serenaAllowedToolsForRole(role: ForgeToolRole): string[] {
  if (!FORGE_TOOL_CATALOG.serena.roles.includes(role)) return []
  const canWrite = FORGE_TOOL_CATALOG.serena.writeRoles.includes(role)
  return canWrite
    ? [...SERENA_MCP_READ_TOOLS, ...SERENA_MCP_WRITE_TOOLS]
    : [...SERENA_MCP_READ_TOOLS]
}

/** Same list via the semantic operation vocabulary, for docs and assertions. */
export function serenaOperationsForRole(role: ForgeToolRole): readonly string[] {
  if (!FORGE_TOOL_CATALOG.serena.roles.includes(role)) return []
  const canWrite = FORGE_TOOL_CATALOG.serena.writeRoles.includes(role)
  return canWrite ? [...SERENA_READ_OPERATIONS, ...SERENA_WRITE_OPERATIONS] : [...SERENA_READ_OPERATIONS]
}

/** Has the rtk shim directory been generated for this workspace? */
export function rtkSeamsPresent(workspace: string): boolean {
  return existsSync(rtkShimDir(workspace))
}

/**
 * Map the runtime's agent role to a Forge tool position. Conservative by
 * design: `lead` maps to lead_pre (read-only) because the adapter does not know
 * the phase here, and an unknown role maps to dev_ops (no analyzer tools at
 * all). Least privilege is the default, never the other way round.
 */
export function forgeToolRoleForAgentRole(role: string | null | undefined): ForgeToolRole {
  const r = (role ?? '').toLowerCase()
  if (r === 'scout') return 'scout'
  if (r === 'architect') return 'architect'
  if (r === 'lead') return 'lead_pre'
  if (r === 'builder' || r === 'smith') return 'smith'
  if (r === 'inspector' || r === 'reviewer') return 'inspector'
  if (r === 'assay' || r === 'verifier') return 'assay'
  return 'dev_ops'
}

