// ---------------------------------------------------------------------------
// VENDOR BLOCKS — one generated block, replicated into every vendor pointer file,
// regenerated by command and checked by the lint.
//
// Pirated from OpenContext's `oc init` (0xranx/OpenContext, MIT): their agent artefacts
// live between `<!-- OPENCONTEXT:START -->` and `<!-- OPENCONTEXT:END -->`, a re-run
// replaces exactly that span, an unchanged render writes nothing, and a file with no
// markers is appended to rather than clobbered. Their guardrails are also one constant
// replicated into every skill and command they generate.
//
// What we keep: the mechanism, and the discipline that every vendor file's block is
// derived from `AGENTS.md` rather than retyped. What we do NOT copy is the part our
// VENDOR-ADAPTERS.md forbids — we never create a vendor file, and the block stays a
// POINTER plus the four load-bearing rules, never a second copy of the handbook.
//
// The anchor check is what makes replication safe: each guardrail names the AGENTS.md
// sentence it is backed by, so a handbook edit that removes the source fails the gate
// instead of leaving a generated file asserting a rule the repo no longer has.
// ---------------------------------------------------------------------------

export const BLOCK_START = '<!-- FORGE:HANDBOOK:BEGIN -->'
export const BLOCK_END = '<!-- FORGE:HANDBOOK:END -->'

export type Guardrail = {
  /** Vendor-facing phrasing, readable without the handbook. */
  text: string
  /** The handbook sentence that must still exist, or this guardrail is orphaned. */
  anchoredBy: string
}

export const GUARDRAILS: readonly Guardrail[] = [
  {
    text: 'Only the Builder role commits. Scout, Assay and Inspector never do.',
    anchoredBy: 'Commit on the worker branch only when the role is Builder',
  },
  {
    text: 'Route every failure through the durable capture framework; a swallowed catch is a defect.',
    anchoredBy: 'Route every failure that reaches a seam through the durable error-capture framework',
  },
  {
    text: 'Never special-case one listing (Casa Luar or any other) in application code.',
    anchoredBy: 'Special-case Casa Luar or any one listing in application code',
  },
  {
    text: 'Never commit secrets or `.env.local`.',
    anchoredBy: 'Commit secrets or `.env.local`',
  },
]

/**
 * Files that MAY receive a generated block. Membership is not a promise they exist: we
 * point at the handbook from files the tools already created, and we never invent a
 * vendor file to have somewhere to write (that is VENDOR-ADAPTERS.md's rule).
 */
export const MANAGED_VENDOR_FILES = [
  'CLAUDE.md',
  'WARP.md',
  'AGENTS.local.md',
  '.windsurfrules',
  '.clinerules',
  'GEMINI.md',
] as const

export const HANDBOOK_READ_ORDER = [
  'AGENTS.md',
  'docs/agent/ORIENTATION.md',
  'docs/agent/packets/<STORY-ID>.md',
  'docs/agent/MEMORY.md',
] as const

export const HARNESS_COMMANDS = [
  { command: 'pnpm forge:manifest <STORY-ID>', what: 'the ranked files to read for a story' },
  { command: 'pnpm forge:packet-lint', what: 'the harness gate (packets, skills, maps, this block)' },
  { command: 'pnpm test:harness', what: 'the harness tests' },
  { command: 'pnpm forge:batch:status', what: 'read-only engine and batch state' },
] as const

/**
 * The block itself. Everything in it is derived from the constants above, so a stale
 * vendor file is a diff, not an archaeology exercise.
 */
export function renderVendorBlock(guardrails: readonly Guardrail[] = GUARDRAILS): string {
  const lines: string[] = []
  lines.push(BLOCK_START)
  lines.push('')
  lines.push('Adapter block — GENERATED by `pnpm forge:sync-agents`. Do not hand-edit.')
  lines.push('')
  lines.push('This file is a pointer, not a second copy of the rules. Read the handbook:')
  for (const path of HANDBOOK_READ_ORDER) lines.push(`- \`${path}\``)
  lines.push('')
  lines.push('Load-bearing rules (source `AGENTS.md`; the lint fails if a source sentence disappears):')
  for (const guardrail of guardrails) lines.push(`- ${guardrail.text}`)
  lines.push('')
  lines.push('Commands:')
  for (const item of HARNESS_COMMANDS) lines.push(`- \`${item.command}\` — ${item.what}`)
  lines.push('')
  lines.push('Regenerate with `pnpm forge:sync-agents`; check with `pnpm forge:sync-agents --check`.')
  lines.push('')
  lines.push(BLOCK_END)
  return `${lines.join('\n')}\n`
}

/**
 * Replace the managed span in place, append when the markers are absent, and return the
 * input unchanged when there is nothing to write — an idempotent re-run must be a no-op
 * rather than a byte-identical rewrite.
 */
export function upsertVendorBlock(current: string | null, block: string): string {
  const next = (block.endsWith('\n') ? block : `${block}\n`).replace(/\n+$/, '\n')
  if (!current || current.trim() === '') return next

  const start = current.indexOf(BLOCK_START)
  const end = current.indexOf(BLOCK_END)
  if (start === -1 || end === -1 || end < start) {
    // No markers (or malformed ones): append rather than guess at what to replace.
    const base = current.endsWith('\n') ? current : `${current}\n`
    return `${base}\n${next}`
  }
  const before = current.slice(0, start).replace(/\s+$/, '')
  const after = current.slice(end + BLOCK_END.length).replace(/^\s+/, '')
  return `${[before, next.replace(/\n$/, ''), after].filter((part) => part.length > 0).join('\n\n')}\n`
}

/** True when this file carries a managed block at all. */
export function hasVendorBlock(content: string): boolean {
  return content.includes(BLOCK_START) && content.includes(BLOCK_END)
}

/**
 * A block that differs from a fresh render is drift: someone hand-edited a generated
 * file, or a guardrail changed and the file was never regenerated.
 */
export function vendorBlockDrifted(content: string, block = renderVendorBlock()): boolean {
  if (!hasVendorBlock(content)) return false
  const start = content.indexOf(BLOCK_START)
  const end = content.indexOf(BLOCK_END) + BLOCK_END.length
  const onDisk = content.slice(start, end).replace(/\s+$/, '')
  return onDisk !== block.replace(/\s+$/, '')
}

/**
 * Guardrails whose backing sentence is gone from the handbook.
 *
 * This is the difference between replicating a rule and inventing one: the text is a
 * translation, the anchor is the source, and a translation without its source fails.
 */
export function orphanedGuardrails(
  agentsMd: string,
  guardrails: readonly Guardrail[] = GUARDRAILS,
): Guardrail[] {
  const normalize = (value: string) => value.replace(/\s+/g, ' ').trim()
  const haystack = normalize(agentsMd)
  return guardrails.filter((guardrail) => !haystack.includes(normalize(guardrail.anchoredBy)))
}
