//! Moved from `property.rs` (move only): PropertyRow, PropertyRelationRow, CachedPropertyRelationRow, PropertyAdminSummaryRow, PropertyAdminRecordRow, map_admin_summary, map_admin_record.

#[allow(unused_imports)]
use super::*;

#[derive(Debug, FromRow)]
pub(super) struct PropertyRow {
    pub(super) id: String,
    pub(super) name: Option<String>,
    pub(super) legal_owner_name: Option<String>,
    pub(super) catastro_number: Option<String>,
    pub(super) registry_entry: Option<String>,
    pub(super) finca_number: Option<String>,
    pub(super) registry_section: Option<String>,
    pub(super) status: String,
    pub(super) archived_at: Option<DateTime<Utc>>,
    pub(super) address_line1: Option<String>,
    pub(super) location: Option<String>,
    pub(super) street_number: Option<String>,
    pub(super) street_name: Option<String>,
    pub(super) unit_number: Option<String>,
    pub(super) city: Option<String>,
    pub(super) state_or_province: Option<String>,
    pub(super) neighborhood: Option<String>,
    pub(super) postal_code: Option<String>,
    pub(super) country: Option<String>,
    pub(super) iso_country_code: Option<String>,
}

#[derive(Debug, FromRow)]
pub(super) struct PropertyRelationRow {
    pub(super) id: String,
    pub(super) name: Option<String>,
    pub(super) legal_owner_name: Option<String>,
    pub(super) catastro_number: Option<String>,
    pub(super) registry_entry: Option<String>,
    pub(super) finca_number: Option<String>,
    pub(super) registry_section: Option<String>,
    pub(super) status: String,
    pub(super) archived_at: Option<DateTime<Utc>>,
    pub(super) address_line1: Option<String>,
    pub(super) location: Option<String>,
    pub(super) street_number: Option<String>,
    pub(super) street_name: Option<String>,
    pub(super) unit_number: Option<String>,
    pub(super) city: Option<String>,
    pub(super) state_or_province: Option<String>,
    pub(super) neighborhood: Option<String>,
    pub(super) postal_code: Option<String>,
    pub(super) country: Option<String>,
    pub(super) iso_country_code: Option<String>,
    pub(super) relation_type: String,
    pub(super) relation_status: Option<String>,
}

#[derive(Debug, FromRow)]
pub(super) struct CachedPropertyRelationRow {
    pub(super) person_id: String,
    pub(super) id: String,
    pub(super) name: Option<String>,
    pub(super) legal_owner_name: Option<String>,
    pub(super) catastro_number: Option<String>,
    pub(super) registry_entry: Option<String>,
    pub(super) finca_number: Option<String>,
    pub(super) registry_section: Option<String>,
    pub(super) status: String,
    pub(super) archived_at: Option<DateTime<Utc>>,
    pub(super) address_line1: Option<String>,
    pub(super) location: Option<String>,
    pub(super) street_number: Option<String>,
    pub(super) street_name: Option<String>,
    pub(super) unit_number: Option<String>,
    pub(super) city: Option<String>,
    pub(super) state_or_province: Option<String>,
    pub(super) neighborhood: Option<String>,
    pub(super) postal_code: Option<String>,
    pub(super) country: Option<String>,
    pub(super) iso_country_code: Option<String>,
    pub(super) relation_type: String,
    pub(super) relation_status: Option<String>,
}

#[derive(Debug, FromRow)]
pub(super) struct PropertyAdminSummaryRow {
    pub(super) id: String,
    pub(super) name: String,
    pub(super) status: String,
    pub(super) slug: Option<String>,
    pub(super) location: Option<String>,
    pub(super) list_price: Option<String>,
    pub(super) property_type: Option<String>,
    pub(super) is_active_listing: bool,
    pub(super) is_published: bool,
    pub(super) archived: bool,
    pub(super) image_count: i64,
    pub(super) video_count: i64,
}

#[derive(Debug, FromRow)]
pub(super) struct PropertyAdminRecordRow {
    pub(super) id: String,
    pub(super) source_metadata:
        sqlx::types::Json<std::collections::BTreeMap<String, serde_json::Value>>,
    pub(super) regrid_fields:
        sqlx::types::Json<std::collections::BTreeMap<String, serde_json::Value>>,
    pub(super) stellar_property_id: Option<String>,
    pub(super) stellar_updated_at: Option<String>,
    pub(super) name: String,
    pub(super) slug: Option<String>,
    pub(super) status: String,
    pub(super) featured: bool,
    pub(super) is_active_listing: bool,
    pub(super) is_published: bool,
    pub(super) property_type: Option<String>,
    pub(super) has_ocean_view: bool,
    pub(super) has_bay_view: bool,
    pub(super) has_beach_view: bool,
    pub(super) has_harbor_view: bool,
    pub(super) has_island_view: bool,
    pub(super) has_mountain_view: bool,
    pub(super) has_sunrise_view: bool,
    pub(super) has_sunset_view: bool,
    pub(super) has_water_access: bool,
    pub(super) has_beach_access: bool,
    pub(super) has_pool: bool,
    pub(super) has_generator: bool,
    pub(super) has_solar: bool,
    pub(super) is_furnished: bool,
    pub(super) is_gated: bool,
    pub(super) list_price: Option<String>,
    pub(super) original_list_price: Option<String>,
    pub(super) location: Option<String>,
    pub(super) address_line1: Option<String>,
    pub(super) street_number: Option<String>,
    pub(super) street_name: Option<String>,
    pub(super) unit_number: Option<String>,
    pub(super) city: Option<String>,
    pub(super) state_or_province: Option<String>,
    pub(super) neighborhood: Option<String>,
    pub(super) postal_code: Option<String>,
    pub(super) country: Option<String>,
    pub(super) iso_country_code: Option<String>,
    pub(super) latitude: Option<String>,
    pub(super) longitude: Option<String>,
    pub(super) bedrooms: Option<String>,
    pub(super) bathrooms: Option<String>,
    pub(super) bathrooms_full: Option<String>,
    pub(super) bathrooms_half: Option<String>,
    pub(super) square_feet: Option<String>,
    pub(super) lot_size: Option<String>,
    pub(super) lot_size_units: Option<String>,
    pub(super) lot_size_acres: Option<String>,
    pub(super) lot_size_sqft: Option<String>,
    pub(super) road_frontage_feet: Option<String>,
    pub(super) road_surface_type: Option<String>,
    pub(super) lot_description: Option<String>,
    pub(super) utilities_notes: Option<String>,
    pub(super) catastro_number: Option<String>,
    pub(super) buildability: Option<String>,
    pub(super) slope_description: Option<String>,
    pub(super) pool_potential: Option<String>,
    pub(super) road_adjacency: Option<String>,
    pub(super) utilities_availability: Option<String>,
    pub(super) hoa_status: Option<String>,
    pub(super) view_description: Option<String>,
    pub(super) year_built: Option<String>,
    pub(super) stories: Option<String>,
    pub(super) parking_spaces: Option<String>,
    pub(super) short_description: Option<String>,
    pub(super) editorial_description: Option<String>,
    pub(super) public_remarks: Option<String>,
    pub(super) seo_title: Option<String>,
    pub(super) seo_description: Option<String>,
    pub(super) hero_title: Option<String>,
    pub(super) tagline: Option<String>,
    pub(super) architecture_notes: Option<String>,
    pub(super) amenities_notes: Option<String>,
    pub(super) lifestyle_notes: Option<String>,
    pub(super) listing_agent_name: Option<String>,
    pub(super) listing_agent_email: Option<String>,
    pub(super) listing_agent_phone: Option<String>,
    pub(super) listing_office: Option<String>,
    pub(super) legal_owner_name: Option<String>,
    pub(super) listing_identifier: Option<String>,
    pub(super) registry_entry: Option<String>,
    pub(super) finca_number: Option<String>,
    pub(super) registry_section: Option<String>,
    pub(super) seller_person_id: Option<String>,
    pub(super) seller_name: Option<String>,
    pub(super) archived: bool,
    pub(super) image_count: i64,
    pub(super) video_count: i64,
    pub(super) document_count: i64,
    pub(super) created_at: Option<String>,
    pub(super) updated_at: Option<String>,
    pub(super) listing_contract_date: Option<String>,
    pub(super) expiration_date: Option<String>,
    pub(super) listing_type: Option<String>,
    pub(super) agent_mls_id: Option<String>,
    pub(super) tax_id: Option<String>,
    pub(super) tax_year: Option<String>,
    pub(super) annual_tax: Option<String>,
    pub(super) legal_description: Option<String>,
    pub(super) zoning: Option<String>,
    pub(super) total_area_sqft: Option<String>,
    pub(super) heated_area_source: Option<String>,
    pub(super) ownership_type: Option<String>,
    pub(super) hoa_details: Option<String>,
    pub(super) showing_instructions: Option<String>,
    pub(super) occupant_type: Option<String>,
}

pub(super) fn map_admin_summary(row: PropertyAdminSummaryRow) -> PropertyAdminSummary {
    PropertyAdminSummary {
        id: row.id,
        name: row.name,
        status: row.status,
        slug: row.slug,
        location: row.location,
        list_price: row.list_price,
        property_type: row.property_type,
        is_active_listing: row.is_active_listing,
        is_published: row.is_published,
        archived: row.archived,
        image_count: row.image_count,
        video_count: row.video_count,
    }
}

pub(super) fn map_admin_record(row: PropertyAdminRecordRow) -> PropertyAdminRecord {
    PropertyAdminRecord {
        id: row.id,
        source_metadata: row.source_metadata.0,
        regrid_fields: row.regrid_fields.0,
        stellar_property_id: row.stellar_property_id,
        stellar_updated_at: row.stellar_updated_at,
        name: row.name,
        slug: row.slug,
        status: row.status,
        featured: row.featured,
        is_active_listing: row.is_active_listing,
        is_published: row.is_published,
        property_type: row.property_type,
        has_ocean_view: row.has_ocean_view,
        has_bay_view: row.has_bay_view,
        has_beach_view: row.has_beach_view,
        has_harbor_view: row.has_harbor_view,
        has_island_view: row.has_island_view,
        has_mountain_view: row.has_mountain_view,
        has_sunrise_view: row.has_sunrise_view,
        has_sunset_view: row.has_sunset_view,
        has_water_access: row.has_water_access,
        has_beach_access: row.has_beach_access,
        has_pool: row.has_pool,
        has_generator: row.has_generator,
        has_solar: row.has_solar,
        is_furnished: row.is_furnished,
        is_gated: row.is_gated,
        list_price: row.list_price,
        original_list_price: row.original_list_price,
        location: row.location,
        address_line1: row.address_line1,
        street_number: row.street_number,
        street_name: row.street_name,
        unit_number: row.unit_number,
        city: row.city,
        state_or_province: row.state_or_province,
        neighborhood: row.neighborhood,
        postal_code: row.postal_code,
        country: row.country,
        iso_country_code: row.iso_country_code,
        latitude: row.latitude,
        longitude: row.longitude,
        bedrooms: row.bedrooms,
        bathrooms: row.bathrooms,
        bathrooms_full: row.bathrooms_full,
        bathrooms_half: row.bathrooms_half,
        square_feet: row.square_feet,
        lot_size: row.lot_size,
        lot_size_units: row.lot_size_units,
        lot_size_acres: row.lot_size_acres,
        lot_size_sqft: row.lot_size_sqft,
        road_frontage_feet: row.road_frontage_feet,
        road_surface_type: row.road_surface_type,
        lot_description: row.lot_description,
        utilities_notes: row.utilities_notes,
        catastro_number: row.catastro_number,
        buildability: row.buildability,
        slope_description: row.slope_description,
        pool_potential: row.pool_potential,
        road_adjacency: row.road_adjacency,
        utilities_availability: row.utilities_availability,
        hoa_status: row.hoa_status,
        view_description: row.view_description,
        year_built: row.year_built,
        stories: row.stories,
        parking_spaces: row.parking_spaces,
        short_description: row.short_description,
        editorial_description: row.editorial_description,
        public_remarks: row.public_remarks,
        seo_title: row.seo_title,
        seo_description: row.seo_description,
        hero_title: row.hero_title,
        tagline: row.tagline,
        architecture_notes: row.architecture_notes,
        amenities_notes: row.amenities_notes,
        lifestyle_notes: row.lifestyle_notes,
        listing_agent_name: row.listing_agent_name,
        listing_agent_email: row.listing_agent_email,
        listing_agent_phone: row.listing_agent_phone,
        listing_office: row.listing_office,
        legal_owner_name: row.legal_owner_name,
        listing_identifier: row.listing_identifier,
        registry_entry: row.registry_entry,
        finca_number: row.finca_number,
        registry_section: row.registry_section,
        seller_person_id: row.seller_person_id,
        seller_name: row.seller_name,
        archived: row.archived,
        image_count: row.image_count,
        video_count: row.video_count,
        document_count: row.document_count,
        created_at: row.created_at,
        updated_at: row.updated_at,
        stellar: PropertyStellarDetails {
            listing_contract_date: row.listing_contract_date,
            expiration_date: row.expiration_date,
            listing_type: row.listing_type,
            agent_mls_id: row.agent_mls_id,
            tax_id: row.tax_id,
            tax_year: row.tax_year,
            annual_tax: row.annual_tax,
            legal_description: row.legal_description,
            zoning: row.zoning,
            total_area_sqft: row.total_area_sqft,
            heated_area_source: row.heated_area_source,
            ownership_type: row.ownership_type,
            hoa_details: row.hoa_details,
            showing_instructions: row.showing_instructions,
            occupant_type: row.occupant_type,
        },
    }
}
