#!/usr/bin/env bash
# Render (and check) the legacy-test parity ledger.
#
# 465 legacy TypeScript test files are the executable statement of the old engine's contracts
# (`docs/agent/OLD-ENGINE-CONTRACT-RESTORATION.md` §2-3). They cannot run against Rust, so each
# file is converted into a Rust test that does — and this script is the only thing that can answer
# "how many are left".
#
#   bash scripts/legacy-test-parity.sh          # render docs/agent/LEGACY-TEST-PARITY.md
#   bash scripts/legacy-test-parity.sh --check  # fail if a legacy file has no status row
#
# The hand-maintained file is the status TSV; this file is generated from it.
set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

STATUS="docs/agent/legacy-test-parity/status.tsv"
OUT="docs/agent/LEGACY-TEST-PARITY.md"

if [ ! -f "$STATUS" ]; then
  echo "missing $STATUS" >&2
  exit 1
fi

find legacy -name '*.test.ts' -o -name '*.test.tsx' | LC_ALL=C sort > /tmp/legacy-parity-files.txt
total=$(wc -l < /tmp/legacy-parity-files.txt | tr -d ' ')

# Every status row must name a legacy file that exists, and every legacy file must have a row:
# a converted suite that silently skips files is the failure this ledger exists to prevent.
cut -f1 "$STATUS" | grep -v '^#' | LC_ALL=C sort > /tmp/legacy-parity-status.txt
missing_status=$(comm -23 /tmp/legacy-parity-files.txt /tmp/legacy-parity-status.txt | wc -l | tr -d ' ')
stale_status=$(comm -13 /tmp/legacy-parity-files.txt /tmp/legacy-parity-status.txt | wc -l | tr -d ' ')

if [ "${1:-}" = "--check" ] && [ "$missing_status" != "0" ]; then
  echo "FAIL: $missing_status legacy test file(s) have no status row:"
  comm -23 /tmp/legacy-parity-files.txt /tmp/legacy-parity-status.txt | head -20
  exit 1
fi

{
  echo "# Legacy test parity — every one of the 465"
  echo
  echo "Generated by \`bash scripts/legacy-test-parity.sh\` from \`docs/agent/legacy-test-parity/status.tsv\`."
  echo "Do not edit this file; edit the status TSV. The 465 files are the old engine's own statements about"
  echo "itself (\`docs/agent/OLD-ENGINE-CONTRACT-RESTORATION.md\` §2). A file is \`ported\` only when a Rust test"
  echo "that runs against the Rust engine asserts the same behaviour and fails if the seam is re-cut."
  echo
  echo "| status | meaning |"
  echo "| --- | --- |"
  echo "| \`ported\` | Rust test exists, runs green, asserts the legacy behaviour |"
  echo "| \`in_force_unported\` | Rust honours the contract, no Rust test pins it yet |"
  echo "| \`missing_capability\` | the contract is gone from Rust — needs code, not only a test |"
  echo "| \`diverged\` | Rust does something *else* here — the legacy assertion would fail |"
  echo "| \`retired\` | intentionally not wanted in the Rust product (reason recorded) |"
  echo "| \`held_back\` | Captain's carve-out (WhatsApp, Marketing) |"
  echo "| \`unassessed\` | not read yet |"
  echo
  echo "## Counts"
  echo
  printf -- '- legacy test files: **%s**\n' "$total"
  for s in ported in_force_unported missing_capability diverged retired held_back unassessed; do
    n=$(awk -F'\t' -v s="$s" '$2==s' "$STATUS" | wc -l | tr -d ' ')
    printf -- '- %s: **%s**\n' "$s" "$n"
  done
  printf -- '- rows not matching a legacy file: **%s**\n' "$stale_status"
  echo
  echo "## Ledger"
  echo
  echo "| # | legacy test file | status | Rust home | note |"
  echo "| --- | --- | --- | --- | --- |"
  awk -F'\t' 'BEGIN{n=0} /^#/ {next} {n++; printf "| %d | `%s` | %s | %s | %s |\n", n, $1, $2, ($3==""?"-":$3), ($4==""?"-":$4)}' "$STATUS"
} > "$OUT"

echo "wrote $OUT — $total files, $missing_status without a status row, $stale_status stale rows"
