#!/usr/bin/env bash
# Render (and check) the legacy-test parity ledger.
#
# 465 legacy TypeScript test files are the executable statement of the old engine's contracts
# (`docs/agent/OLD-ENGINE-CONTRACT-RESTORATION.md` §2-3). They cannot run against Rust, so each
# file is converted into a Rust test that does — and this script is the only thing that can answer
# "how many are left".
#
#   bash scripts/legacy-test-parity.sh          # render docs/agent/LEGACY-TEST-PARITY.md
#   bash scripts/legacy-test-parity.sh --check  # fail if a legacy file has no status row
#
# The hand-maintained file is the status TSV; this file is generated from it.
set -uo pipefail

cd "$(dirname "$0")/.." || exit 1

STATUS="docs/agent/legacy-test-parity/status.tsv"
COVERED="docs/agent/legacy-test-parity/already-covered.tsv"
OUT="docs/agent/LEGACY-TEST-PARITY.md"

if [ ! -f "$STATUS" ]; then
  echo "missing $STATUS" >&2
  exit 1
fi

# The queue shrinks by machine evidence, not by hand: `scripts/legacy-test-merge-scan.py` writes the
# legacy files that already have an equivalent Rust test. A hand-written status row always wins over
# the scan (a judgement is better than a heuristic), so the scan only fills `unassessed` rows.
#   bash scripts/legacy-test-parity.sh --scan   # refresh the scan, then render
if [ "${1:-}" = "--scan" ]; then
  python3 scripts/legacy-test-merge-scan.py || exit 1
  # Keep the area map in step with the scan: the ledger joins it, and a stale map is a wrong column.
  python3 scripts/legacy-test-domain-map.py --write || exit 1
fi

EFFECTIVE=/tmp/legacy-parity-effective.tsv
if [ -f "$COVERED" ]; then
  awk -F'\t' '
    FILENAME==ARGV[1] { if ($0 !~ /^#/ && $1 != "") { c_status[$1]=$3; c_tier[$1]=$2; c_ev[$1]=$4; c_note[$1]=$5 } ; next }
    /^#/ { next }
    {
      s=$2; home=$3; note=$4
      if (s=="unassessed" && ($1 in c_status)) {
        s=c_status[$1]
        home=c_ev[$1]
        note=c_note[$1] " [" c_tier[$1] "]"
      }
      print $1 "\t" s "\t" home "\t" note
    }' "$COVERED" "$STATUS" > "$EFFECTIVE"
else
  awk -F'\t' '/^#/ {next} {print $1 "\t" $2 "\t" $3 "\t" $4}' "$STATUS" > "$EFFECTIVE"
fi

find legacy -name '*.test.ts' -o -name '*.test.tsx' | LC_ALL=C sort > /tmp/legacy-parity-files.txt
total=$(wc -l < /tmp/legacy-parity-files.txt | tr -d ' ')

# What each file is about (`scripts/legacy-test-domain-map.py --write`): joined into the ledger so
# the queue can be read area by area, and summarised in docs/agent/LEGACY-TEST-DOMAINS.md.
DOMAINS="docs/agent/legacy-test-parity/domains.tsv"
AREA_MAP=/tmp/legacy-parity-area.tsv
if [ -f "$DOMAINS" ]; then
  awk -F'\t' 'NR>1 {print $1 "\t" $2}' "$DOMAINS" > "$AREA_MAP"
else
  : > "$AREA_MAP"
  echo "note: $DOMAINS is missing — run python3 scripts/legacy-test-domain-map.py --write" >&2
fi
areas=$(cut -f2 "$AREA_MAP" | sort -u | grep -c . || true)

# Every status row must name a legacy file that exists, and every legacy file must have a row:
# a converted suite that silently skips files is the failure this ledger exists to prevent.
cut -f1 "$STATUS" | grep -v '^#' | LC_ALL=C sort > /tmp/legacy-parity-status.txt
missing_status=$(comm -23 /tmp/legacy-parity-files.txt /tmp/legacy-parity-status.txt | wc -l | tr -d ' ')
stale_status=$(comm -13 /tmp/legacy-parity-files.txt /tmp/legacy-parity-status.txt | wc -l | tr -d ' ')

if [ "${1:-}" = "--check" ] && [ "$missing_status" != "0" ]; then
  echo "FAIL: $missing_status legacy test file(s) have no status row:"
  comm -23 /tmp/legacy-parity-files.txt /tmp/legacy-parity-status.txt | head -20
  exit 1
fi

{
  echo "# Legacy test parity — every one of the 465"
  echo
  echo "Generated by \`bash scripts/legacy-test-parity.sh\` from \`docs/agent/legacy-test-parity/status.tsv\`."
  echo "Do not edit this file; edit the status TSV. The 465 files are the old engine's own statements about"
  echo "itself (\`docs/agent/OLD-ENGINE-CONTRACT-RESTORATION.md\` §2). A file is \`ported\` only when a Rust test"
  echo "that runs against the Rust engine asserts the same behaviour and fails if the seam is re-cut."
  echo "The \`area\` column is what the file is *about* (\`docs/agent/LEGACY-TEST-DOMAINS.md\`); the status"
  echo "column is how far along it is. Work the queue by area: unassessed files inside one area are one"
  echo "piece of context, not forty separate ones."
  echo
  echo "| status | meaning |"
  echo "| --- | --- |"
  echo "| \`ported\` | Rust test exists, runs green, asserts the legacy behaviour |"
  echo "| \`in_force_unported\` | Rust honours the contract, no Rust test pins it yet |"
  echo "| \`missing_capability\` | the contract is gone from Rust — needs code, not only a test |"
  echo "| \`diverged\` | Rust does something *else* here — the legacy assertion would fail |"
  echo "| \`retired\` | intentionally not wanted in the Rust product (reason recorded) |"
  echo "| \`held_back\` | Captain's carve-out (WhatsApp, Marketing) |"
  echo "| \`already_covered\` | an equivalent Rust test already exists (machine scan; Rust tests >= legacy cases) |"
  echo "| \`gap\` | an equivalent Rust test exists for part of the file; the delta is in the note |"
  echo "| \`unassessed\` | not read yet — this is the conversion queue |"
  echo
  echo "## Counts"
  echo
  printf -- '- legacy test files: **%s**\n' "$total"
  for s in ported in_force_unported missing_capability diverged retired held_back already_covered gap unassessed; do
    n=$(awk -F'\t' -v s="$s" '$2==s' "$EFFECTIVE" | wc -l | tr -d ' ')
    printf -- '- %s: **%s**\n' "$s" "$n"
  done
  printf -- '- rows not matching a legacy file: **%s**\n' "$stale_status"
  printf -- '- areas: **%s** (\`docs/agent/LEGACY-TEST-DOMAINS.md\`)\n' "$areas"
  echo
  echo "## Ledger"
  echo
  echo "| # | legacy test file | area | status | Rust home | note |"
  echo "| --- | --- | --- | --- | --- | --- |"
  awk -F'\t' 'BEGIN{n=0}
    FILENAME==ARGV[1] { area[$1]=$2; next }
    { n++; a=($1 in area)?area[$1]:"-"; printf "| %d | `%s` | %s | %s | %s | %s |\n", n, $1, a, $2, ($3==""?"-":$3), ($4==""?"-":$4) }' "$AREA_MAP" "$EFFECTIVE"
} > "$OUT"

queue=$(awk -F'\t' '$2=="unassessed"' "$EFFECTIVE" | wc -l | tr -d ' ')
echo "wrote $OUT — $total files, $queue still in the conversion queue, $missing_status without a status row, $stale_status stale rows"
