/**
 * RUST PARITY LEDGER — generated evidence, not an opinion.
 *
 *   node --import tsx scripts/rust-parity-ledger.ts      # writes docs/rust-parity-ledger.md
 *
 * WHY: "how far along is the Rust port" deserves a number that comes from the repository rather than from a
 * summary. This walks the import graph from the entry points that actually ship, then reports for every TypeScript
 * module under `db/` and `services/` whether shipped code can still reach it — printed beside the live Rust route
 * table so the two surfaces are visible in one place.
 *
 * WHAT IT DOES NOT PROVE — read this before deleting anything:
 *   * Reachability is not behaviour. A module can be reachable and dead, and it can be unreachable yet still be
 *     the production path (a dynamic `import(someString)` or a registry built from strings is invisible here).
 *   * "Candidate" means "no shipped file imports it", which is the START of a review, not the end. The referencers
 *     are printed next to each candidate precisely so a human can see whether the only caller is a test, a script,
 *     or nothing at all.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

const ROOTS = ['app', 'components', 'lib', 'workflow_app', 'scripts']
const SUBJECTS = ['db', 'services']
const SKIP = new Set(['node_modules', '.next', '.vercel', '.git', 'target'])
const EXTS = ['', '.ts', '.tsx', '/index.ts', '/index.tsx']

function walk(dir: string, out: string[] = []): string[] {
  let entries: string[]
  try {
    entries = readdirSync(dir)
  } catch {
    return out
  }
  for (const entry of entries) {
    if (SKIP.has(entry)) continue
    const full = join(dir, entry)
    const info = statSync(full)
    if (info.isDirectory()) walk(full, out)
    else if (/\.(ts|tsx)$/.test(entry)) out.push(full)
  }
  return out
}

function specs(file: string): string[] {
  const text = readFileSync(file, 'utf8')
  const found = new Set<string>()
  for (const match of text.matchAll(/(?:from|import)\s*\(?\s*['"]([^'"]+)['"]/g)) found.add(match[1])
  for (const match of text.matchAll(/require\(\s*['"]([^'"]+)['"]\s*\)/g)) found.add(match[1])
  return [...found]
}

function resolveSpec(spec: string, fromFile: string): string | null {
  const base =
    spec.startsWith('@/')
      ? resolve(spec.slice(2))
      : spec.startsWith('.')
        ? resolve(dirname(fromFile), spec)
        : null
  if (base === null) return null
  for (const ext of EXTS) {
    const candidate = base + ext
    try {
      if (statSync(candidate).isFile()) return candidate
    } catch {
      // try the next extension
    }
  }
  return null
}

const roots = ROOTS.map((root) => resolve(root))
const allFiles = roots.flatMap((root) => walk(root))
const subjects = SUBJECTS.flatMap((dir) => walk(resolve(dir)))

// Reachability: breadth-first from the shipped roots.
const reachable = new Set<string>()
const queue = [...allFiles]
while (queue.length > 0) {
  const file = queue.pop() as string
  if (reachable.has(file)) continue
  reachable.add(file)
  for (const spec of specs(file)) {
    const target = resolveSpec(spec, file)
    if (target !== null && !reachable.has(target)) queue.push(target)
  }
}

// Referencers: who mentions each subject module, so a candidate can be judged rather than trusted.
const referencers = new Map<string, string[]>()
for (const file of [...allFiles, ...subjects]) {
  for (const spec of specs(file)) {
    const target = resolveSpec(spec, file)
    if (target === null) continue
    referencers.set(target, [...(referencers.get(target) ?? []), relative(file)])
  }
}

function relative(file: string): string {
  return file.replace(`${process.cwd()}/`, '')
}

const routes = (() => {
  try {
    const text = readFileSync(resolve('rust/server/src/api/routes.rs'), 'utf8')
    return [...text.matchAll(/\.route\("([^"]+)"/g)].map((match) => match[1])
  } catch {
    return []
  }
})()

const candidates = subjects.filter((file) => !reachable.has(file))
const reached = subjects.filter((file) => reachable.has(file))

const lines: string[] = [
  '# Rust parity ledger',
  '',
  'Generated by `node --import tsx scripts/rust-parity-ledger.ts` — do not hand-edit. Regenerate after any change',
  'to the import graph, and before acting on a deletion candidate.',
  '',
  '## The live Rust surface',
  '',
  `${routes.length} routes mounted in \`rust/server/src/api/routes.rs\`:`,
  '',
  ...routes.map((route) => `- \`${route}\``),
  '',
  '## TypeScript modules under the subjects',
  '',
  `- \`db/\` and \`services/\`: **${subjects.length}** modules`,
  `- reachable from shipped code: **${reached.length}**`,
  `- not imported by any shipped file (REVIEW, not delete): **${candidates.length}**`,
  '',
  'Reachable means "some file under app/, components/, lib/, workflow_app/ or scripts/ imports it, directly or',
  'through another module". The list below is a review queue, with each candidate\'s referencers printed.',
  '',
  '### Review candidates',
  '',
  ...(candidates.length === 0
    ? ['(none)']
    : candidates.flatMap((file) => {
        const who = referencers.get(file) ?? []
        const from = who.length === 0 ? '**nothing imports it, not even a test**' : who.join(', ')
        return [`- \`${relative(file)}\` — referenced by: ${from}`]
      })),
  '',
  '## What this cannot tell you',
  '',
  '- A module reached only through a dynamic string import looks unreachable here; check the route and message',
  '  registries by hand before deleting.',
  '- Reachability says nothing about whether the Rust counterpart is exercised in production. That needs a',
  '  receipt, not a graph.',
  '',
]

writeFileSync(resolve('docs/rust-parity-ledger.md'), `${lines.join('\n')}\n`)
process.stdout.write(
  `rust-parity-ledger: ${subjects.length} subject modules, ${reached.length} reachable, ` +
    `${candidates.length} review candidates, ${routes.length} Rust routes\n`,
)
