import type { EngineeringLineModel } from './types'

/** Mock board. Swap `loadEngineeringLine()` for listStoryboardStories + work items. */
export const ENGINEERING_LINE_FIXTURE: EngineeringLineModel = {
  freshnessUtc: '2026-09-12 18:38',
  roles: ['Scout Flash', 'Lead Pro', 'Smith Flash', 'Assay'],
  stories: [
    {
      id: 'CRM-28',
      title: 'P&S Amendment → Canonical Term Delta',
      workstream: 'CRM',
      status: 'Open',
      bucket: 'open',
      intent:
        'Amend and align purchase & sale terms for active listings so deal structure, pricing, and closing conditions stay canonical.',
      waitsFor: [],
      completion: 0,
      onBench: true,
      routeIntent: 'SOLO',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'services/contract, lib/storyboard-data.ts',
      prohibitedScope: 'workflow_engine/',
      acceptance: [
        'Term delta is a first-class field on the contract snapshot',
        'Existing listings still render without a delta',
        'Assay frozen commands pass',
      ],
    },
    {
      id: 'ENG-FORGE-SESSION-ID-01',
      title: 'Story-resident OpenCode session continuity',
      workstream: 'TECH',
      status: 'Open',
      bucket: 'open',
      intent: 'Persist the session id the harness actually used. Do not export cost yet.',
      waitsFor: [],
      completion: 0,
      onBench: true,
      routeIntent: 'SMITH',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'agent-runtime/opencode/',
      prohibitedScope: 'workflow_engine/',
      acceptance: ['Evidence stores opencodeSessionId or null', 'Failed spawn is null'],
    },
    {
      id: 'ENG-FORGE-PACKET-OBS-01',
      title: 'Context packet compiler (observer mode)',
      workstream: 'TECH',
      status: 'Open',
      bucket: 'open',
      intent: 'Compile a provenance-bearing packet. Do not replace the live prompt yet.',
      waitsFor: [],
      completion: 0,
      onBench: true,
      routeIntent: 'SOLO',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'workflow_app/forge/forge-context-packet.ts',
      prohibitedScope: 'workflow_engine/',
      acceptance: ['Deterministic manifest', 'Sibling files omitted unless allowedScope'],
      line: { station: 'ready' },
    },
    {
      id: 'ENG-FORGE-V13',
      title: 'Forge SDLC V13 dogfood',
      workstream: 'TECH',
      status: 'In Progress',
      bucket: 'open',
      intent: 'Live serial lane on PROD.',
      waitsFor: [],
      completion: 40,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'workflow_app/forge/',
      prohibitedScope: '',
      acceptance: ['QA is authority'],
      line: {
        station: 'running',
        node: 'lead_solo_implement',
        attempt: 1,
        widgets: '1.2k',
        instanceId: 'b3a91424-e85d-4832-82af-ca8a6e21836b',
      },
    },
    {
      id: 'ENG-PROJECTS-ANCHOR-02',
      title: 'Projects projection: effective anchor source',
      workstream: 'PROJECTS',
      status: 'In Progress',
      bucket: 'open',
      intent: 'Report the effective anchor, not a guessed one.',
      waitsFor: [],
      completion: 70,
      onBench: false,
      routeIntent: 'SMITH',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'ui/projects/',
      prohibitedScope: '',
      acceptance: ['testv2 projection 14/14'],
      line: {
        station: 'running',
        node: 'qa',
        attempt: 2,
        widgets: '0.4k',
        instanceId: 'forge-engine-69584',
      },
    },
    {
      id: 'ENG-FORGE-OPENCODE-DOGFOOD-01',
      title: 'OpenCode dogfood — repeated failure watch',
      workstream: 'TECH',
      status: 'Hold',
      bucket: 'open',
      intent: 'Prove the serial Smith door.',
      waitsFor: [],
      completion: 0,
      onBench: false,
      routeIntent: 'SMITH',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'agent-runtime/opencode/',
      prohibitedScope: '',
      acceptance: ['HOLD names the door'],
      line: {
        station: 'hold',
        reason: 'Smith does not choose its own scope',
        instanceId: 'opencode-178904',
      },
    },
    {
      id: 'ENG-FORGE-TELEMETRY-07',
      title: 'ForgeDB telemetry — latency + acquisitions',
      workstream: 'TECH',
      status: 'Complete',
      bucket: 'closed',
      intent: 'stats() reports averages, never NaN.',
      waitsFor: [],
      completion: 100,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'db/forge-db.ts',
      prohibitedScope: '',
      acceptance: ['Asking for stats opens no connection'],
      line: { station: 'done', sha: 'a3f9c21', qa: 'passed' },
    },
    {
      id: 'ENG-FORGE-UI-SIGNALS-03',
      title: 'Observer rehydrate after worker restart',
      workstream: 'TECH',
      status: 'Complete',
      bucket: 'closed',
      intent: 'RETRY_UNCHANGED_INPUT sees attempt 1 after process death.',
      waitsFor: [],
      completion: 100,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'workflow_app/forge/forge-observer/',
      prohibitedScope: '',
      acceptance: ['seed() advances seq'],
      line: { station: 'done', sha: 'e571b98', qa: 'passed' },
    },
    {
      id: 'CRM-25',
      title: 'Outbound External Action / Correlation Loop',
      workstream: 'CRM',
      status: 'Hold',
      bucket: 'open',
      intent: 'Correlation loop stays on the engine token.',
      waitsFor: [],
      completion: 0,
      onBench: false,
      routeIntent: 'SMITH',
      seamsNamed: false,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'ENG-FORGE-CONVERGENCE-READMODEL-01',
      title: 'Candidate iteration and convergence read model',
      workstream: 'TECH',
      status: 'Hold',
      bucket: 'open',
      intent: 'Replace the wallpaper strip with Line.',
      waitsFor: [],
      completion: 0,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: false,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'ENG-FORGE-FASTLANE-01',
      title: 'Make FORGE_SDLC FAST lane actually fast',
      workstream: 'TECH',
      status: 'Hold',
      bucket: 'open',
      intent: 'FAST is a graph, not a vibe.',
      waitsFor: [],
      completion: 0,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: false,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'DEV-PULL-CADENCE-01',
      title: 'Pull PROD down to DEV on a cadence, as a runbook',
      workstream: 'TECH',
      status: 'Planned',
      bucket: 'backlog',
      intent: 'Do not casually forge:sync-history.',
      waitsFor: [],
      completion: 0,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: false,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'DREAM-DEPLOY-RECEIPT-01',
      title: 'DREAM: trustworthy deployment receipt from the host (Vercel)',
      workstream: 'TECH',
      status: 'Planned',
      bucket: 'backlog',
      intent: 'Human domain until a reliable host signal exists.',
      waitsFor: [],
      completion: 0,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: false,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'ENG-FORGE-COST-01',
      title: 'Per-attempt usage capture: raw tokens + vendor-reported cost',
      workstream: 'TECH',
      status: 'Planned',
      bucket: 'backlog',
      intent: 'Needs session id first. Widgets stay the internal unit.',
      waitsFor: ['ENG-FORGE-SESSION-ID-01'],
      completion: 0,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: false,
      depsClear: false,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'OPS-02',
      title: 'Client Administration',
      workstream: 'OPS',
      status: 'Complete',
      bucket: 'closed',
      intent: '',
      waitsFor: [],
      completion: 100,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: true,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'OPS-03',
      title: 'Property Administration',
      workstream: 'OPS',
      status: 'Complete',
      bucket: 'closed',
      intent: '',
      waitsFor: [],
      completion: 100,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: true,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'CRM-07',
      title: 'WhatsApp Intake',
      workstream: 'CRM',
      status: 'Deferred',
      bucket: 'next',
      intent: '',
      waitsFor: [],
      completion: 10,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: false,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'CRM-29',
      title: 'V2 — Buyer-to-Property Matching + Curated Collections',
      workstream: 'CRM',
      status: 'Deferred',
      bucket: 'next',
      intent: '',
      waitsFor: [],
      completion: 0,
      onBench: false,
      routeIntent: 'SOLO',
      seamsNamed: false,
      depsClear: true,
      allowedScope: '',
      prohibitedScope: '',
      acceptance: [],
    },
    {
      id: 'ENG-FORGE-SPLIT-VALVE-07',
      title: 'SPLIT children on isolated worktrees',
      workstream: 'TECH',
      status: 'In Progress',
      bucket: 'open',
      intent: 'Two children, sibling files only.',
      waitsFor: [],
      completion: 60,
      onBench: false,
      routeIntent: 'SPLIT',
      seamsNamed: true,
      depsClear: true,
      allowedScope: 'workflow_app/forge/',
      prohibitedScope: '',
      acceptance: ['Join on SHA', 'scope lock at file grain'],
      line: {
        station: 'running',
        node: 'smith_split_work',
        attempt: 1,
        widgets: '2.1k',
        instanceId: 'split-7f3e',
        children: [
          { label: 'Child 1', sha: 'a3f9c2d' },
          { label: 'Child 2', sha: 'b7e1a9f' },
        ],
      },
    },
  ],
}

export function loadEngineeringLine(): EngineeringLineModel {
  return ENGINEERING_LINE_FIXTURE
}
