//! Vendor blocks — one generated block, replicated into every vendor pointer file, regenerated by
//! command and checked by the lint. Ported from the retired `lib/agent-vendor-block.ts` (deleted with
//! the TypeScript application in `4cf98110`).
//!
//! What is kept: the mechanism, and the discipline that every vendor file's block is derived from
//! `AGENTS.md` rather than retyped. What is NOT copied: we never create a vendor file, and the block
//! stays a POINTER plus the four load-bearing rules, never a second copy of the handbook.
//!
//! The anchor check is what makes replication safe: each guardrail names the `AGENTS.md` sentence it is
//! backed by, so a handbook edit that removes the source FAILS the gate instead of leaving a generated
//! file asserting a rule the repo no longer has.

pub const BLOCK_START: &str = "<!-- FORGE:HANDBOOK:BEGIN -->";
pub const BLOCK_END: &str = "<!-- FORGE:HANDBOOK:END -->";

pub struct Guardrail {
    /// Vendor-facing phrasing, readable without the handbook.
    pub text: &'static str,
    /// The handbook sentence that must still exist, or this guardrail is orphaned.
    pub anchored_by: &'static str,
}

pub const GUARDRAILS: [Guardrail; 4] = [
    Guardrail {
        text: "Only the Builder role commits. Scout, Assay and Inspector never do.",
        anchored_by: "Commit on the worker branch only when the role is Builder",
    },
    Guardrail {
        text: "Route every failure through the durable capture framework; a swallowed catch is a defect.",
        anchored_by: "Route every failure that reaches a seam through the durable error-capture framework",
    },
    Guardrail {
        text: "Never special-case one listing (Casa Luar or any other) in application code.",
        anchored_by: "Special-case Casa Luar or any one listing in application code",
    },
    Guardrail {
        text: "Never commit secrets or `.env.local`.",
        anchored_by: "Commit secrets or `.env.local`",
    },
];

/// Files that MAY receive a generated block. Membership is not a promise they exist: we point at the
/// handbook from files the tools already created, and we never invent a vendor file to have somewhere
/// to write.
pub const MANAGED_VENDOR_FILES: [&str; 6] = [
    "CLAUDE.md",
    "WARP.md",
    "AGENTS.local.md",
    ".windsurfrules",
    ".clinerules",
    "GEMINI.md",
];

pub const HANDBOOK_READ_ORDER: [&str; 4] = [
    "AGENTS.md",
    "docs/agent/ORIENTATION.md",
    "docs/agent/packets/<STORY-ID>.md",
    "docs/agent/MEMORY.md",
];

pub const HARNESS_COMMANDS: [(&str, &str); 4] = [
    ("pnpm forge:manifest <STORY-ID>", "the ranked files to read for a story"),
    (
        "pnpm forge:packet-lint",
        "the harness gate (packets, skills, maps, this block)",
    ),
    ("pnpm test:harness", "the harness tests"),
    ("pnpm forge:batch:status", "read-only engine and batch state"),
];

/// The block itself. Everything in it is derived from the constants above, so a stale vendor file is a
/// diff, not an archaeology exercise.
pub fn render_block() -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push(BLOCK_START.to_string());
    lines.push(String::new());
    lines.push("Adapter block — GENERATED by `pnpm forge:sync-agents`. Do not hand-edit.".to_string());
    lines.push(String::new());
    lines.push("This file is a pointer, not a second copy of the rules. Read the handbook:".to_string());
    for path in HANDBOOK_READ_ORDER {
        lines.push(format!("- `{path}`"));
    }
    lines.push(String::new());
    lines.push(
        "Load-bearing rules (source `AGENTS.md`; the lint fails if a source sentence disappears):"
            .to_string(),
    );
    for guardrail in GUARDRAILS {
        lines.push(format!("- {}", guardrail.text));
    }
    lines.push(String::new());
    lines.push("Commands:".to_string());
    for (command, what) in HARNESS_COMMANDS {
        lines.push(format!("- `{command}` — {what}"));
    }
    lines.push(String::new());
    lines.push(
        "Regenerate with `pnpm forge:sync-agents`; check with `pnpm forge:sync-agents --check`."
            .to_string(),
    );
    lines.push(String::new());
    lines.push(BLOCK_END.to_string());
    format!("{}\n", lines.join("\n"))
}

/// Replace the managed span in place, append when the markers are absent, and return the input
/// unchanged when there is nothing to write — an idempotent re-run must be a no-op rather than a
/// byte-identical rewrite.
pub fn upsert_block(current: Option<&str>, block: &str) -> String {
    // `/\n+$/` -> a single `\n`.
    let next = format!("{}\n", block.trim_end_matches('\n'));
    let Some(current) = current else {
        return next;
    };
    if current.trim().is_empty() {
        return next;
    }
    let append = |current: &str| format!("{}\n\n{next}", current.trim_end_matches('\n'));

    let (Some(start), Some(end)) = (current.find(BLOCK_START), current.find(BLOCK_END)) else {
        // No markers (or malformed ones): append rather than guess at what to replace.
        return append(current);
    };
    if end < start {
        return append(current);
    }

    let before = current[..start].trim_end();
    let after = current[end + BLOCK_END.len()..].trim_start();
    let middle = next.trim_end_matches('\n');
    let parts: Vec<&str> = [before, middle, after]
        .into_iter()
        .filter(|part| !part.is_empty())
        .collect();
    format!("{}\n", parts.join("\n\n"))
}

/// True when this file carries a managed block at all.
pub fn has_block(content: &str) -> bool {
    content.contains(BLOCK_START) && content.contains(BLOCK_END)
}

/// A block that differs from a fresh render is drift: someone hand-edited a generated file, or a
/// guardrail changed and the file was never regenerated.
pub fn block_drifted(content: &str, block: &str) -> bool {
    if !has_block(content) {
        return false;
    }
    let start = content.find(BLOCK_START).unwrap_or(0);
    let end = content.find(BLOCK_END).unwrap_or(0) + BLOCK_END.len();
    content[start..end].trim_end() != block.trim_end()
}

/// Guardrails whose backing sentence is gone from the handbook.
///
/// This is the difference between replicating a rule and inventing one: the text is a translation, the
/// anchor is the source, and a translation without its source fails.
pub fn orphaned_guardrails<'a>(agents_md: &str, guardrails: &'a [Guardrail]) -> Vec<&'a Guardrail> {
    let normalize = |value: &str| value.split_whitespace().collect::<Vec<_>>().join(" ");
    let haystack = normalize(agents_md);
    guardrails
        .iter()
        .filter(|guardrail| !haystack.contains(&normalize(guardrail.anchored_by)))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_fresh_render_never_drifts_and_a_hand_edit_does() {
        let block = render_block();
        let fresh = upsert_block(Some("# Adapter\n"), &block);
        assert!(!block_drifted(&fresh, &block));

        let edited = fresh.replace("Only the Builder role commits", "Anyone may commit");
        assert!(block_drifted(&edited, &block));
    }

    #[test]
    fn upsert_is_idempotent_and_appends_when_there_are_no_markers() {
        let block = render_block();
        let once = upsert_block(Some("# Adapter\n"), &block);
        assert_eq!(once, upsert_block(Some(&once), &block));
        assert!(once.starts_with("# Adapter\n\n"));
        assert_eq!(upsert_block(None, &block), block);
    }

    #[test]
    fn a_file_without_markers_is_never_reported_as_drifted() {
        assert!(!block_drifted("# Adapter\nnothing here yet\n", &render_block()));
    }

    #[test]
    fn an_orphaned_guardrail_is_the_one_whose_sentence_left_the_handbook() {
        // The real handbook reads `Commit secrets or \`.env.local\`.` — capital C, because it is a list
        // item. This fixture keeps that casing: the check is exact, and a fixture that paraphrases the
        // sentence it is anchoring tests nothing.
        let handbook = "Commit secrets or `.env.local`. builder only.";
        let orphans: Vec<&str> = orphaned_guardrails(handbook, &GUARDRAILS)
            .iter()
            .map(|guardrail| guardrail.anchored_by)
            .collect();
        assert_eq!(orphans.len(), 3);
        assert!(!orphans.contains(&"Commit secrets or `.env.local`"));
    }
}
