import type { FlightRecorderTrace, TraceEvent } from './types';

export const CORRELATION_ID = 'b7f3e8d2-4c61-4a77-9c6e-8a91f8e3e47f';

const TRACE_START = '2025-05-20T10:14:32.145-04:00';

function at(offsetMs: number): string {
  const start = Date.parse(TRACE_START);
  return new Date(start + offsetMs).toISOString();
}

const IDS = {
  cmdReceived: 'evt_01_cmd_received',
  aggregateCreated: 'evt_02_agg_created',
  dealCreated: 'evt_03_deal_created',
  wfStarted: 'evt_8b1a2c3d4e5f6a7b',
  taskCreated: 'evt_91c2d3e4f5b6a7c8',
  taskAssigned: 'evt_06_task_assigned',
  envelopeCreated: 'evt_07_env_created',
  envelopeSent: 'evt_08_env_sent',
  dealSaved: 'evt_09_deal_saved',
  taskSaved1: 'evt_10_task_saved',
  recipientViewed: 'evt_11_recipient_viewed',
  recipientSigned: 'evt_12_recipient_signed',
  documentSigned: 'evt_13_document_signed',
  wfAdvanced: 'evt_14_wf_advanced',
  activityRecorded: 'evt_15_activity_recorded',
  nextTaskCreated: 'evt_16_next_task',
  taskSaved2: 'evt_17_task_saved_2',
  timelineUpdated: 'evt_18_timeline_updated',
} as const;

const events: TraceEvent[] = [
  {
    id: IDS.cmdReceived,
    correlationId: CORRELATION_ID,
    causationId: null,
    kind: 'Command',
    type: 'CreateDealCommandReceived',
    title: 'Create Deal Command Received',
    subtitle: 'Command',
    system: 'API Gateway',
    status: 'Success',
    occurredAt: at(0),
    offsetMs: 0,
    durationMs: 13,
    details: {
      Deal: 'DEAL-2025-000123',
      By: 'lisa@culebraluxe.com',
    },
    payload: {
      command: 'CreateDeal',
      dealId: 'DEAL-2025-000123',
      initiatedBy: 'lisa@culebraluxe.com',
      source: 'api-gateway',
    },
    tags: ['command', 'deal', 'ingress'],
    relatedEventIds: [
      { id: IDS.aggregateCreated, title: 'Deal Aggregate Created', offsetMs: 13 },
    ],
  },
  {
    id: IDS.aggregateCreated,
    correlationId: CORRELATION_ID,
    causationId: IDS.cmdReceived,
    kind: 'DomainEvent',
    type: 'DealAggregateCreated',
    title: 'Deal Aggregate Created',
    subtitle: 'Domain Event',
    system: 'Domain Model',
    status: 'Success',
    occurredAt: at(13),
    offsetMs: 13,
    durationMs: 4,
    details: {
      Status: 'Draft',
      Version: '1',
    },
    payload: {
      dealId: 'DEAL-2025-000123',
      status: 'Draft',
      version: 1,
    },
    tags: ['domain', 'aggregate', 'deal'],
    relatedEventIds: [
      { id: IDS.cmdReceived, title: 'Create Deal Command Received', offsetMs: -13 },
      { id: IDS.dealCreated, title: 'Deal Created', offsetMs: 4 },
    ],
  },
  {
    id: IDS.dealCreated,
    correlationId: CORRELATION_ID,
    causationId: IDS.aggregateCreated,
    kind: 'DomainEvent',
    type: 'DealCreated',
    title: 'Deal Created',
    subtitle: 'Domain Event',
    system: 'Domain Model',
    status: 'Success',
    occurredAt: at(17),
    offsetMs: 17,
    durationMs: 16,
    details: {
      Property: '123 Ocean View Dr',
      Buyer: 'Maria & Juan Rodriguez',
    },
    payload: {
      dealId: 'DEAL-2025-000123',
      property: '123 Ocean View Dr, Dorado, PR',
      buyers: ['Maria Rodriguez', 'Juan Rodriguez'],
    },
    tags: ['domain', 'deal', 'created'],
    relatedEventIds: [
      { id: IDS.aggregateCreated, title: 'Deal Aggregate Created', offsetMs: -4 },
      { id: IDS.wfStarted, title: 'Workflow Instance Started', offsetMs: 16 },
    ],
  },
  {
    id: IDS.wfStarted,
    correlationId: CORRELATION_ID,
    causationId: IDS.dealCreated,
    kind: 'Workflow',
    type: 'WorkflowInstanceStarted',
    title: 'Workflow Instance Started',
    subtitle: 'Workflow',
    system: 'Workflow Engine',
    status: 'Success',
    occurredAt: at(33),
    offsetMs: 33,
    durationMs: 18,
    details: {
      Workflow: 'Purchase Transaction v2.3.1',
      Instance: 'wf_8f3a9c2e',
    },
    payload: {
      workflowId: 'purchase-transaction',
      version: '2.3.1',
      workflowInstanceId: 'wf_8f3a9c2e',
      dealId: 'DEAL-2025-000123',
    },
    tags: ['workflow', 'instance'],
    relatedEventIds: [
      { id: IDS.dealCreated, title: 'Deal Created', offsetMs: -16 },
      { id: IDS.taskCreated, title: 'Task Created', offsetMs: 18 },
    ],
  },
  {
    id: IDS.taskCreated,
    correlationId: CORRELATION_ID,
    causationId: IDS.wfStarted,
    kind: 'Workflow',
    type: 'TaskCreated',
    title: 'Task Created',
    subtitle: 'Workflow',
    system: 'Workflow Engine',
    status: 'Success',
    occurredAt: at(51),
    offsetMs: 51,
    durationMs: 12,
    details: {
      Task: 'Send P&S to Buyers',
      Assignee: 'Lisa Rodriguez',
    },
    payload: {
      taskId: 'task_92b1e7c4',
      workflowInstanceId: 'wf_8f3a9c2e',
      taskType: 'Send Purchase & Sale',
      title: 'Send P&S to Buyers',
      description: 'Send Purchase & Sale Agreement via BoldSign for signatures',
      assigneeId: 'user_lisa_001',
      assigneeName: 'Lisa Rodriguez',
      dueDate: '2025-05-20T14:00:00-04:00',
      priority: 'High',
      dealId: 'DEAL-2025-000123',
      createdBy: 'system',
      createdAt: '2025-05-20T10:14:32.196-04:00',
    },
    tags: ['workflow', 'task', 'creation', 'high-priority'],
    relatedEventIds: [
      { id: IDS.wfStarted, title: 'Workflow Instance Started', offsetMs: -18 },
      { id: IDS.taskAssigned, title: 'Task Assigned', offsetMs: 12 },
      { id: IDS.envelopeCreated, title: 'BoldSign Envelope Created', offsetMs: 25 },
    ],
  },
  {
    id: IDS.taskAssigned,
    correlationId: CORRELATION_ID,
    causationId: IDS.taskCreated,
    kind: 'Task',
    type: 'TaskAssigned',
    title: 'Task Assigned',
    subtitle: 'Task Service',
    system: 'Task Service',
    status: 'Success',
    occurredAt: at(63),
    offsetMs: 63,
    durationMs: 13,
    details: {
      To: 'Lisa Rodriguez',
      Due: 'May 20, 2025 2:00 PM',
    },
    payload: {
      taskId: 'task_92b1e7c4',
      assigneeId: 'user_lisa_001',
      assigneeName: 'Lisa Rodriguez',
      dueDate: '2025-05-20T14:00:00-04:00',
    },
    tags: ['task', 'assignment'],
    relatedEventIds: [
      { id: IDS.taskCreated, title: 'Task Created', offsetMs: -12 },
    ],
  },
  {
    id: IDS.envelopeCreated,
    correlationId: CORRELATION_ID,
    causationId: IDS.taskCreated,
    kind: 'Integration',
    type: 'BoldSignEnvelopeCreated',
    title: 'BoldSign Envelope Created',
    subtitle: 'Integration',
    system: 'BoldSign',
    status: 'Success',
    occurredAt: at(76),
    offsetMs: 76,
    durationMs: 624,
    details: {
      Envelope: 'env_7f8c2d1a',
      Template: 'Purchase & Sale Agreement',
    },
    payload: {
      envelopeId: 'env_7f8c2d1a',
      template: 'Purchase & Sale Agreement',
      dealId: 'DEAL-2025-000123',
      taskId: 'task_92b1e7c4',
    },
    tags: ['integration', 'boldsign', 'envelope'],
    relatedEventIds: [
      { id: IDS.taskCreated, title: 'Task Created', offsetMs: -25 },
      { id: IDS.envelopeSent, title: 'BoldSign Envelope Sent', offsetMs: 624 },
    ],
  },
  {
    id: IDS.envelopeSent,
    correlationId: CORRELATION_ID,
    causationId: IDS.envelopeCreated,
    kind: 'Integration',
    type: 'BoldSignEnvelopeSent',
    title: 'BoldSign Envelope Sent',
    subtitle: 'Integration',
    system: 'BoldSign',
    status: 'Success',
    occurredAt: at(700),
    offsetMs: 700,
    durationMs: 257,
    details: {
      To: 'maria.rodriguez@email.com',
      Cc: 'juan.rodriguez@email.com',
    },
    payload: {
      envelopeId: 'env_7f8c2d1a',
      recipients: ['maria.rodriguez@email.com', 'juan.rodriguez@email.com'],
    },
    tags: ['integration', 'boldsign', 'sent'],
    relatedEventIds: [
      { id: IDS.envelopeCreated, title: 'BoldSign Envelope Created', offsetMs: -624 },
      { id: IDS.recipientViewed, title: 'BoldSign Recipient Viewed', offsetMs: 1042 },
    ],
  },
  {
    id: IDS.dealSaved,
    correlationId: CORRELATION_ID,
    causationId: IDS.dealCreated,
    kind: 'Persistence',
    type: 'DealSaved',
    title: 'Deal Saved',
    subtitle: 'Persistence',
    system: 'PostgreSQL',
    status: 'Success',
    occurredAt: at(957),
    offsetMs: 957,
    durationMs: 16,
    details: {
      Table: 'deal',
      ID: 'DEAL-2025-000123',
    },
    payload: {
      table: 'deal',
      id: 'DEAL-2025-000123',
      op: 'insert',
    },
    tags: ['persistence', 'postgres', 'deal'],
    relatedEventIds: [
      { id: IDS.dealCreated, title: 'Deal Created', offsetMs: -940 },
    ],
  },
  {
    id: IDS.taskSaved1,
    correlationId: CORRELATION_ID,
    causationId: IDS.taskCreated,
    kind: 'Persistence',
    type: 'TaskSaved',
    title: 'Task Saved',
    subtitle: 'Persistence',
    system: 'PostgreSQL',
    status: 'Success',
    occurredAt: at(973),
    offsetMs: 973,
    durationMs: 14,
    details: {
      Table: 'task',
      ID: 'task_92b1e7c4',
    },
    payload: {
      table: 'task',
      id: 'task_92b1e7c4',
      op: 'insert',
    },
    tags: ['persistence', 'postgres', 'task'],
    relatedEventIds: [
      { id: IDS.taskCreated, title: 'Task Created', offsetMs: -922 },
    ],
  },
  {
    id: IDS.recipientViewed,
    correlationId: CORRELATION_ID,
    causationId: IDS.envelopeSent,
    kind: 'Integration',
    type: 'BoldSignRecipientViewed',
    title: 'BoldSign Recipient Viewed',
    subtitle: 'Integration',
    system: 'BoldSign',
    status: 'Success',
    occurredAt: at(1742),
    offsetMs: 1742,
    durationMs: 625,
    details: {
      Envelope: 'env_7f8c2d1a',
      Recipient: 'maria.rodriguez@email.com',
    },
    payload: {
      envelopeId: 'env_7f8c2d1a',
      recipient: 'maria.rodriguez@email.com',
      action: 'viewed',
    },
    tags: ['integration', 'boldsign', 'viewed'],
    relatedEventIds: [
      { id: IDS.envelopeSent, title: 'BoldSign Envelope Sent', offsetMs: -1042 },
      { id: IDS.recipientSigned, title: 'BoldSign Recipient Signed', offsetMs: 625 },
    ],
  },
  {
    id: IDS.recipientSigned,
    correlationId: CORRELATION_ID,
    causationId: IDS.recipientViewed,
    kind: 'Integration',
    type: 'BoldSignRecipientSigned',
    title: 'BoldSign Recipient Signed',
    subtitle: 'Integration',
    system: 'BoldSign',
    status: 'Success',
    occurredAt: at(2367),
    offsetMs: 2367,
    durationMs: 11,
    details: {
      Envelope: 'env_7f8c2d1a',
      Recipient: 'maria.rodriguez@email.com',
    },
    payload: {
      envelopeId: 'env_7f8c2d1a',
      recipient: 'maria.rodriguez@email.com',
      action: 'signed',
    },
    tags: ['integration', 'boldsign', 'signed'],
    relatedEventIds: [
      { id: IDS.recipientViewed, title: 'BoldSign Recipient Viewed', offsetMs: -625 },
      { id: IDS.documentSigned, title: 'Document Signed', offsetMs: 11 },
    ],
  },
  {
    id: IDS.documentSigned,
    correlationId: CORRELATION_ID,
    causationId: IDS.recipientSigned,
    kind: 'DomainEvent',
    type: 'DocumentSigned',
    title: 'Document Signed',
    subtitle: 'Domain Event',
    system: 'Domain Model',
    status: 'Success',
    occurredAt: at(2378),
    offsetMs: 2378,
    durationMs: 208,
    details: {
      Document: 'Purchase & Sale Agreement',
      'Signed By': 'Maria Rodriguez',
    },
    payload: {
      documentType: 'Purchase & Sale Agreement',
      signedBy: 'Maria Rodriguez',
      envelopeId: 'env_7f8c2d1a',
      dealId: 'DEAL-2025-000123',
    },
    tags: ['domain', 'document', 'signed'],
    relatedEventIds: [
      { id: IDS.recipientSigned, title: 'BoldSign Recipient Signed', offsetMs: -11 },
      { id: IDS.wfAdvanced, title: 'Workflow Advanced', offsetMs: 208 },
    ],
  },
  {
    id: IDS.wfAdvanced,
    correlationId: CORRELATION_ID,
    causationId: IDS.documentSigned,
    kind: 'Workflow',
    type: 'WorkflowAdvanced',
    title: 'Workflow Advanced',
    subtitle: 'Workflow',
    system: 'Workflow Engine',
    status: 'Success',
    occurredAt: at(2586),
    offsetMs: 2586,
    durationMs: 11,
    details: {
      From: 'Awaiting Buyer Signatures',
      To: 'Buyer One Signed',
    },
    payload: {
      workflowInstanceId: 'wf_8f3a9c2e',
      fromState: 'Awaiting Buyer Signatures',
      toState: 'Buyer One Signed',
    },
    tags: ['workflow', 'transition'],
    relatedEventIds: [
      { id: IDS.documentSigned, title: 'Document Signed', offsetMs: -208 },
      { id: IDS.nextTaskCreated, title: 'Next Task Created', offsetMs: 271 },
    ],
  },
  {
    id: IDS.activityRecorded,
    correlationId: CORRELATION_ID,
    causationId: IDS.documentSigned,
    kind: 'Persistence',
    type: 'ActivityRecorded',
    title: 'Activity Recorded',
    subtitle: 'Persistence',
    system: 'PostgreSQL',
    status: 'Success',
    occurredAt: at(2597),
    offsetMs: 2597,
    durationMs: 12,
    details: {
      Table: 'activity',
      ID: 'act_5d7e8f1a',
    },
    payload: {
      table: 'activity',
      id: 'act_5d7e8f1a',
      kind: 'document_signed',
    },
    tags: ['persistence', 'activity'],
    relatedEventIds: [
      { id: IDS.documentSigned, title: 'Document Signed', offsetMs: -219 },
    ],
  },
  {
    id: IDS.nextTaskCreated,
    correlationId: CORRELATION_ID,
    causationId: IDS.wfAdvanced,
    kind: 'Task',
    type: 'TaskCreated',
    title: 'Next Task Created',
    subtitle: 'Task Service',
    system: 'Task Service',
    status: 'Success',
    occurredAt: at(2857),
    offsetMs: 2857,
    durationMs: 11,
    details: {
      Task: 'Confirm Earnest Money',
      Assignee: 'Maria Rodriguez',
    },
    payload: {
      taskId: 'task_a3f9b2d1',
      taskType: 'Confirm Earnest Money',
      assigneeName: 'Maria Rodriguez',
      dealId: 'DEAL-2025-000123',
      workflowInstanceId: 'wf_8f3a9c2e',
    },
    tags: ['task', 'creation'],
    relatedEventIds: [
      { id: IDS.wfAdvanced, title: 'Workflow Advanced', offsetMs: -271 },
      { id: IDS.taskSaved2, title: 'Task Saved', offsetMs: 11 },
    ],
  },
  {
    id: IDS.taskSaved2,
    correlationId: CORRELATION_ID,
    causationId: IDS.nextTaskCreated,
    kind: 'Persistence',
    type: 'TaskSaved',
    title: 'Task Saved',
    subtitle: 'Persistence',
    system: 'PostgreSQL',
    status: 'Success',
    occurredAt: at(2868),
    offsetMs: 2868,
    durationMs: 2,
    details: {
      Table: 'task',
      ID: 'task_a3f9b2d1',
    },
    payload: {
      table: 'task',
      id: 'task_a3f9b2d1',
      op: 'insert',
    },
    tags: ['persistence', 'postgres', 'task'],
    relatedEventIds: [
      { id: IDS.nextTaskCreated, title: 'Next Task Created', offsetMs: -11 },
    ],
  },
  {
    id: IDS.timelineUpdated,
    correlationId: CORRELATION_ID,
    causationId: IDS.documentSigned,
    kind: 'DomainEvent',
    type: 'DealTimelineUpdated',
    title: 'Deal Timeline Updated',
    subtitle: 'Domain Event',
    system: 'Domain Model',
    status: 'Success',
    occurredAt: at(2870),
    offsetMs: 2870,
    durationMs: 8,
    details: {
      'Event Count': '1',
      'Last Event': 'Document Signed',
    },
    payload: {
      dealId: 'DEAL-2025-000123',
      eventCount: 1,
      lastEvent: 'Document Signed',
    },
    tags: ['domain', 'timeline'],
    relatedEventIds: [
      { id: IDS.documentSigned, title: 'Document Signed', offsetMs: -492 },
    ],
  },
];

export const DEAL_TRACE_FIXTURE: FlightRecorderTrace = {
  summary: {
    correlationId: CORRELATION_ID,
    rootTitle: 'Create Deal',
    rootKind: 'Command',
    durationMs: 2847,
    eventCount: events.length,
    systemCount: 7,
    status: 'Completed',
    businessContext: {
      dealId: 'DEAL-2025-000123',
      property: '123 Ocean View Dr, Dorado, PR',
      client: 'Maria & Juan Rodriguez',
      workflow: 'Purchase Transaction v2.3.1',
      initiatedBy: 'lisa@culebraluxe.com',
      initiatedAt: '2025-05-20T10:14:32-04:00',
    },
  },
  events,
};

export const SELECTED_EVENT_ID = IDS.taskCreated;
export const EVENT_IDS = IDS;
