// Each action is a distinct entitlement; the second value is its operation kind.
// Keep this catalog aligned with the corresponding SQL seed.
pub(super) const ACTIONS: &[(&str, &str)] = &[
    ("accounting.read", "query"),
    ("accounting.write", "command"),
    ("calendar.read", "query"),
    ("calendar.write", "command"),
    ("cockpit.read", "query"),
    ("comms.read", "query"),
    ("contract.execute", "command"),
    ("contract.read", "query"),
    ("contract.write", "command"),
    ("crm.write", "command"),
    ("deal.read", "query"),
    ("deal.write", "command"),
    ("firm.read", "query"),
    ("firm.write", "command"),
    ("form.read", "query"),
    ("form.write", "command"),
    ("person.read", "query"),
    ("person.write", "command"),
    ("portal.read", "query"),
    ("project.read", "query"),
    ("project.write", "command"),
    ("property.read", "query"),
    ("property.write", "command"),
    ("security.principal.read", "query"),
    ("security.entitlement.manage", "command"),
    ("showing.read", "query"),
    ("showing.write", "command"),
    ("signature.read", "query"),
    ("signature.write", "command"),
    ("vault.issue", "command"),
    ("vault.read", "query"),
    ("vault.write", "command"),
    ("wbs.read", "query"),
    ("wbs.write", "command"),
];
