// Each action is a distinct entitlement; the second value is its operation kind.
// Keep this catalog aligned with the corresponding SQL seed.
//
// An action must appear here to be DECIDABLE by the authorize endpoint, which refuses anything it cannot name. That
// is why `security.identity.resolve` is listed even though no role grants it: the login seam's own operation is
// authorized (granted to the Auth.js edge actor by a policy rule), and an action that cannot be named cannot be
// decided — the seam would have failed closed against a catalog gap rather than against a policy.
pub(super) const ACTIONS: &[(&str, &str)] = &[
    ("accounting.read", "query"),
    ("accounting.write", "command"),
    ("calendar.read", "query"),
    ("calendar.write", "command"),
    ("cockpit.read", "query"),
    ("comms.read", "query"),
    ("contract.execute", "command"),
    ("contract.read", "query"),
    ("contract.write", "command"),
    ("crm.write", "command"),
    ("deal.read", "query"),
    ("deal.write", "command"),
    ("firm.read", "query"),
    ("firm.write", "command"),
    ("form.read", "query"),
    ("form.write", "command"),
    ("guide.public.read", "query"),
    ("person.read", "query"),
    ("person.write", "command"),
    ("portal.read", "query"),
    ("project.read", "query"),
    ("project.write", "command"),
    ("property.public.read", "query"),
    ("property.read", "query"),
    ("property.write", "command"),
    ("security.identity.resolve", "query"),
    ("security.principal.read", "query"),
    ("security.entitlement.manage", "command"),
    ("security.role.manage", "command"),
    ("showing.read", "query"),
    ("showing.write", "command"),
    ("signature.read", "query"),
    ("signature.write", "command"),
    ("tech.access", "query"),
    ("tech.operate", "command"),
    ("vault.issue", "command"),
    ("vault.read", "query"),
    ("vault.write", "command"),
    ("wbs.read", "query"),
    ("wbs.write", "command"),
    ("website.intake.submit", "command"),
];
